#theme: jekyll-theme-cayman
remote_theme: "mmistakes/minimal-mistakes@4.15.2"
minimal_mistakes_skin: "dark"
masthead_title: "Dasha's blog"

# Site Settings
locale                   : "en-US"
title                    : "Hey! You are reading Dasha's blog."
name                     : "Daria HERVIEUX"
description              : "Some posts on JS, Java, Angular and other interesting technical stuff."
search                   : true

# activate pagination - number of posts to show
paginate: 5
paginate_path: "/page:num/"

# Collections
#collections:
#  java:
#    output: true
#    permalink: /:collection/:path/
#  web:
#    output: true
#    permalink: /:collection/:path/

#Profile configuration
author:
  name     : "Daria HERVIEUX"
  avatar   : "/assets/images/author.png"
  bio      : "Curious. Passionate. Software engineer."
  location : "France."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dariahervieux"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/daria-hervieux/"

#comments provider configuration (defaults are configured in the theme)
comments:
  provider       : "staticman_v2"
  staticman:
    branch       : "master"
    moderation   : false

# Social Sharing
social:
  name                   : "Daria HERVIEUX"
  links: https://www.linkedin.com/in/daria-hervieux/


# Plugins (previously gems:)
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jemoji
#safe: false
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-include-cache
  - jekyll-paginate
  - jemoji

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      comments: true
      layout: single
      author_profile: true
      share: true
  - scope:
      path: ""
      type: pages
    values:
      author_profile: true